### ISSUE TITLE
Việt hóa thêm đi

### ISSUE THREAD

**Issue by PTKDrake** [BlackZeroPM/VietHoa#1]
Ông việt hóa plugin PurePerm+PureChat,FactionPro đi

**Comment by BlackZeroPM** [comment]
Đã xong PurePerms, PureChat sẽ hoàn thành sớm nội trong nay mai! Tải PurePerms việt hóa [tại đây
](https://github.com/BlackZeroPM/VietHoa/tree/master/PurePerms)
